import React from 'react'
import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from '@/components/ui/sonner';
import NavBottom from '@/components/Apps/common/NavBottom';
import TopNav from '@/components/Apps/MainMenu/TopNav';
import { poppins } from '@/lib/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({children} : Readonly<{children: React.ReactNode}>) => {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center ${poppins.className}  antialiased`}
      >
        <TopNav />
        {children}
        <NavBottom />
        <Toaster position="top-left" richColors />
      </body>
    </html>
  )
}

export default RootLayout