-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "sessionId" TEXT;

-- AlterTable
ALTER TABLE "PosSession" ADD COLUMN     "cashAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "orderCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "posRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSales" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "transferAmt" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PosSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;
